package projectdetect

import (
	"bytes"
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
)

// Generated-code detection is the fourth detection axis: project types answer
// "what kind of project is this directory", languages answer "what language is
// this file", vendored answers "is this third-party content", and this answers
// "was this file emitted by a tool rather than written by a person". Source-
// analysis tools usually want to skip generated files — protobuf output, mocks,
// OpenAPI clients — because their metrics say nothing about the code humans
// maintain.
//
// Detection runs on two independent signals:
//
//   - Path patterns: regexes against the slash-separated path, exactly like
//     VendorMatcher. These catch conventions where the filename itself is the
//     marker (user.pb.go, api_pb2.py, zz_generated.deepcopy.go, model.g.dart).
//   - Content markers: per-language header substrings scanned over the first
//     few lines. These catch the dominant convention of a tool-written comment
//     preamble — Go's official "// Code generated ... DO NOT EDIT.", protoc's
//     per-language headers, Microsoft's <auto-generated> shape for C#, the
//     "@generated" annotation popular across JS/TS/Rust/PHP, and the universal
//     "DO NOT EDIT" / "Generated by" prefixes the rest of the ecosystem
//     converged on.
//
// The two signals are deliberately exposed separately (MatchPath /
// MatchContent) as well as combined (Match): a tool walking a git tree has
// paths long before it has blob contents, and a blob-content cache keyed by
// SHA has contents but no single authoritative path.

// GeneratedMatcher tests file paths and file contents against patterns
// identifying machine-generated source. The zero value is not usable;
// construct one with NewGeneratedMatcher or DefaultGeneratedMatcher.
type GeneratedMatcher struct {
	mu       sync.RWMutex
	patterns []*regexp.Regexp
	markers  map[string][]string // language id -> lowercase header substrings
}

// defaultGeneratedPathPatterns is a curated, conservative set of filename
// conventions where the path alone proves generation (GitHub-Linguist /
// go-enry derived). Deliberately absent: *_mock.go, mocks/ and *_string.go
// (mockgen/mockery/stringer output always carries the canonical Go
// "// Code generated" header, so the content markers catch it without risking
// hand-written mocks), and loose infixes like *_generated.* or *.generated.*
// (too often hand-written). Extend per matcher with AddPathPattern or globally
// with RegisterGeneratedPathPattern.
var defaultGeneratedPathPatterns = []string{
	// Protocol buffers / gRPC output.
	`\.pb(\.gw)?\.go$`,       // protoc-gen-go, grpc-gateway
	`_pb2(_grpc)?\.py$`,      // protoc Python
	`\.pb\.(cc|h)$`,          // protoc C++
	`\.pb\.swift$`,           // protoc Swift
	`_pb\.(js|ts|d\.ts|rb)$`, // protoc JS / TS / Ruby

	// Go codegen conventions.
	`\.gen\.go$`,                  // oapi-codegen, sqlc, and friends
	`(^|/)zz_generated[^/]*\.go$`, // Kubernetes deepcopy et al.
	`(^|/)wire_gen\.go$`,          // google/wire
	`(^|/)bindata(_assetfs)?\.go$`,

	// Dart build_runner / freezed output.
	`\.(g|freezed)\.dart$`,

	// GraphQL codegen (Relay, graphql-codegen).
	`(^|/)__generated__/`,

	// Dependency lock files.
	`(^|/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|composer\.lock|Gemfile\.lock|poetry\.lock|go\.sum)$`,

	// iOS dependency / build output.
	`(^|/)Pods/`,
	`(^|/)Carthage/Build/`,
}

// defaultGeneratedMarkers maps a language id (as returned by LanguageForPath,
// though MatchContent accepts any id the caller's own detection produces —
// "shell" and "dart" are included even though the extension table doesn't
// know them yet) to header substrings. Each substring is matched against a
// line lowercased, so entries must be lowercase. Kept per-language rather
// than one universal list so a convention established in one ecosystem can't
// misfire in another. Languages without an established convention are simply
// absent — MatchContent returns false for them rather than guessing.
var defaultGeneratedMarkers = map[string][]string{
	"go": {
		// Official convention from cmd/go/internal/generate is the anchored
		// regex `^// Code generated .* DO NOT EDIT\.$`; matching only the
		// leading marker also catches non-canonical variants that drop the
		// suffix.
		"// code generated ",
	},
	"python": {
		"# generated by",
		"# generated automatically",
		"# autogenerated",
		"# this file is autogenerated",
		"# do not edit",
		"# @generated",
	},
	"java": {
		"// generated by",
		"@javax.annotation.generated",
		"@generated",
		"// do not edit",
	},
	"kotlin": {
		"// generated by",
		"@generated",
		"// do not edit",
	},
	"scala": {
		"// generated by",
		"// do not edit",
		"@generated",
	},
	"csharp": {
		// Microsoft's official auto-generated XML comment used by every .NET
		// source generator.
		"// <auto-generated",
		"<auto-generated>",
		"// generated by",
		"// do not edit",
	},
	"javascript": {
		// Bare "@generated" (not "// @generated") because Facebook's
		// convention puts it inside a leading block comment: " * @generated".
		"@generated",
		"// this file is auto-generated",
		"// do not edit",
		"// generated by",
	},
	"typescript": {
		"@generated",
		"// this file is auto-generated",
		"// do not edit",
		"// generated by",
	},
	"rust": {
		"// @generated",
		"// auto-generated",
		"// generated by",
		"// do not edit",
	},
	"ruby": {
		"# @generated",
		"# generated by",
		"# do not edit",
	},
	"swift": {
		"// generated by",
		"// do not edit",
		"// @generated",
	},
	"perl": {
		"# generated by",
		"# do not edit",
	},
	"shell": {
		"# generated by",
		"# do not edit",
		"# @generated",
	},
	"php": {
		"// @generated",
		"// generated by",
		"// do not edit",
		"# generated by",
	},
	"c": {
		"generated by the protocol buffer compiler",
		"// do not edit",
		"/* do not edit",
		"automatically generated",
	},
	"cpp": {
		"generated by the protocol buffer compiler",
		"// do not edit",
		"/* do not edit",
		"automatically generated",
	},
	"dart": {
		"generated code - do not modify", // build_runner banner
		"// do not edit",
		"@generated",
	},
}

// precompiledGeneratedPatterns compiles the built-in path patterns once at
// package init, mirroring precompiledDefaultPatterns in vendored.go. A
// malformed built-in panics at startup — a programming bug, not a runtime
// condition.
var precompiledGeneratedPatterns = func() []*regexp.Regexp {
	compiled := make([]*regexp.Regexp, len(defaultGeneratedPathPatterns))
	for i, p := range defaultGeneratedPathPatterns {
		compiled[i] = regexp.MustCompile(p)
	}
	return compiled
}()

// NewGeneratedMatcher returns an empty matcher — it matches nothing until you
// add path patterns or markers. Use it to opt out of the built-in sets.
func NewGeneratedMatcher() *GeneratedMatcher {
	return &GeneratedMatcher{markers: map[string][]string{}}
}

// DefaultGeneratedMatcher returns a new matcher preloaded with the curated
// built-in path patterns and content markers. The returned matcher is
// independent, so extending it does not affect the package-level IsGenerated.
func DefaultGeneratedMatcher() *GeneratedMatcher {
	m := NewGeneratedMatcher()
	m.patterns = make([]*regexp.Regexp, len(precompiledGeneratedPatterns))
	copy(m.patterns, precompiledGeneratedPatterns)
	for lang, markers := range defaultGeneratedMarkers {
		m.markers[lang] = append([]string(nil), markers...)
	}
	return m
}

// AddPathPattern compiles and appends regexp patterns, each matched against
// the slash-separated path. It returns the first compile error and adds
// nothing in that case.
func (m *GeneratedMatcher) AddPathPattern(patterns ...string) error {
	compiled := make([]*regexp.Regexp, 0, len(patterns))
	for _, p := range patterns {
		re, err := regexp.Compile(p)
		if err != nil {
			return fmt.Errorf("projectdetect: invalid generated pattern %q: %w", p, err)
		}
		compiled = append(compiled, re)
	}
	m.mu.Lock()
	m.patterns = append(m.patterns, compiled...)
	m.mu.Unlock()
	return nil
}

// AddMarker registers content marker substrings for a language id. Markers are
// stored lowercased; matching is against each header line lowercased.
func (m *GeneratedMatcher) AddMarker(language string, markers ...string) {
	lowered := make([]string, len(markers))
	for i, s := range markers {
		lowered[i] = strings.ToLower(s)
	}
	m.mu.Lock()
	m.markers[language] = append(m.markers[language], lowered...)
	m.mu.Unlock()
}

// MatchPath reports whether path matches any registered path pattern. Paths
// are normalised to forward slashes before matching.
func (m *GeneratedMatcher) MatchPath(path string) bool {
	p := filepath.ToSlash(path)
	m.mu.RLock()
	defer m.mu.RUnlock()
	for _, re := range m.patterns {
		if re.MatchString(p) {
			return true
		}
	}
	return false
}

// generatedLineBudget caps how many leading lines MatchContent scans for a
// generator marker. 20 is comfortably past the "copyright header THEN
// generator marker" shape some tools emit (a typical license header is 6–12
// lines plus a blank, marker around line 14).
const generatedLineBudget = 20

// maxGeneratedScan caps how many bytes MatchContent inspects, so a huge
// single-line file can't turn the check into a performance sink. 16 KiB is far
// more than 20 header lines ever occupy.
const maxGeneratedScan = 16 * 1024

// MatchContent reports whether content opens with a known generator marker for
// the given language id. Only the first generatedLineBudget lines (and at most
// maxGeneratedScan bytes) are examined; each line is lowercased and every
// registered marker for the language is tried as a substring. Returns false
// for languages with no registered markers, for empty content, and for binary
// content (a NUL byte in the first 512 bytes).
func (m *GeneratedMatcher) MatchContent(content []byte, language string) bool {
	m.mu.RLock()
	markers := m.markers[language]
	m.mu.RUnlock()
	if len(markers) == 0 || len(content) == 0 {
		return false
	}
	head := content
	if len(head) > 512 {
		head = head[:512]
	}
	if bytes.IndexByte(head, 0) != -1 {
		return false // looks binary
	}
	rest := content
	if len(rest) > maxGeneratedScan {
		rest = rest[:maxGeneratedScan]
	}
	for i := 0; i < generatedLineBudget && len(rest) > 0; i++ {
		line := rest
		if nl := bytes.IndexByte(rest, '\n'); nl != -1 {
			line, rest = rest[:nl], rest[nl+1:]
		} else {
			rest = nil
		}
		lower := strings.ToLower(string(line))
		for _, marker := range markers {
			if strings.Contains(lower, marker) {
				return true
			}
		}
	}
	return false
}

// Match reports whether the file looks generated on either signal: its path
// matches a registered pattern, or its content opens with a generator marker
// for the language inferred from the path's extension.
func (m *GeneratedMatcher) Match(path string, content []byte) bool {
	if m.MatchPath(path) {
		return true
	}
	return m.MatchContent(content, LanguageForPath(path))
}

// sharedGenerated backs the package-level IsGenerated* functions. It is built
// from the defaults and may be extended process-wide via
// RegisterGeneratedPathPattern / RegisterGeneratedMarker.
var sharedGenerated = DefaultGeneratedMatcher()

// IsGeneratedPath reports whether path alone identifies a machine-generated
// file (protobuf output, lock files, zz_generated Go files, ...), using the
// built-in pattern set plus anything added via RegisterGeneratedPathPattern.
func IsGeneratedPath(path string) bool {
	return sharedGenerated.MatchPath(path)
}

// IsGeneratedContent reports whether content opens with a known generator
// marker for the given language id (as returned by LanguageForPath), using the
// built-in marker table plus anything added via RegisterGeneratedMarker.
func IsGeneratedContent(content []byte, language string) bool {
	return sharedGenerated.MatchContent(content, language)
}

// IsGenerated reports whether the file looks machine-generated by path or by
// content. For a matcher you fully control, use a GeneratedMatcher.
func IsGenerated(path string, content []byte) bool {
	return sharedGenerated.Match(path, content)
}

// RegisterGeneratedPathPattern adds path patterns to the process-wide matcher
// used by IsGeneratedPath / IsGenerated. Safe for concurrent use; returns the
// first compile error.
func RegisterGeneratedPathPattern(patterns ...string) error {
	return sharedGenerated.AddPathPattern(patterns...)
}

// RegisterGeneratedMarker adds content markers for a language to the
// process-wide matcher used by IsGeneratedContent / IsGenerated. Safe for
// concurrent use.
func RegisterGeneratedMarker(language string, markers ...string) {
	sharedGenerated.AddMarker(language, markers...)
}
