package projectdetect_test

import (
	"strings"
	"testing"

	"github.com/richardwooding/projectdetect"
)

func TestIsGeneratedPath(t *testing.T) {
	cases := []struct {
		path string
		want bool
	}{
		// Protocol buffers / gRPC output.
		{"api/v1/user.pb.go", true},
		{"api/v1/user.pb.gw.go", true},
		{"gen/service_pb2.py", true},
		{"gen/service_pb2_grpc.py", true},
		{"proto/user.pb.cc", true},
		{"proto/user.pb.h", true},
		{"Sources/user.pb.swift", true},
		{"src/api_pb.js", true},
		{"src/api_pb.d.ts", true},
		{"lib/api_pb.rb", true},
		// Go codegen conventions.
		{"pkg/api/oapi.gen.go", true},
		{"pkg/api/spec.gen.go", true},
		{"apis/v1/zz_generated.deepcopy.go", true},
		{"cmd/server/wire_gen.go", true},
		{"assets/bindata.go", true},
		// Dart / GraphQL / lock files / iOS.
		{"lib/model.g.dart", true},
		{"lib/model.freezed.dart", true},
		{"src/__generated__/Query.ts", true},
		{"package-lock.json", true},
		{"backend/go.sum", true},
		{"Cargo.lock", true},
		{"Pods/Alamofire/Source/Alamofire.swift", true},
		{"Carthage/Build/iOS/Result.framework/x.swift", true},
		// Near-misses — must NOT match.
		{"src/main.go", false},
		{"internal/engine/engine.go", false},
		{"pkg/generate.go", false},  // "generate" isn't a generated convention
		{"pkg/superb.go", false},    // ends in "b.go", not ".pb.go"
		{"scripts/mypb2.py", false}, // no underscore before pb2
		{"pkg/wire_gen_test.go", false},
		{"lib/model.dart", false},
		{"docs/generated-guide.md", false},
		{"handlers/oxygen.go", false}, // ends in "gen.go", not ".gen.go"
	}
	for _, tc := range cases {
		if got := projectdetect.IsGeneratedPath(tc.path); got != tc.want {
			t.Errorf("IsGeneratedPath(%q) = %v, want %v", tc.path, got, tc.want)
		}
	}
}

func TestIsGeneratedContent(t *testing.T) {
	cases := []struct {
		name    string
		lang    string
		content string
		want    bool
	}{
		{"protoc-gen-go", "go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\npackage api\n", true},
		{"mockery", "go", "// Code generated by mockery v2.20.0. DO NOT EDIT.\npackage mocks\n", true},
		{"oapi-codegen", "go", "// Package api provides primitives to interact with the openapi HTTP API.\n//\n// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.\npackage api\n", true},
		{"go case-insensitive", "go", "// CODE GENERATED BY THING. DO NOT EDIT.\npackage x\n", true},
		{"go handwritten", "go", "// Package engine turns commits into frames.\npackage engine\n", false},
		{"protoc python", "python", "# Generated by the protocol buffer compiler.  DO NOT EDIT!\nimport sys\n", true},
		{"python handwritten", "python", "#!/usr/bin/env python\nimport sys\n\ndef main():\n    pass\n", false},
		{"protoc java", "java", "// Generated by the protocol buffer compiler.  DO NOT EDIT!\npackage com.example;\n", true},
		{"csharp auto-generated", "csharp", "//------------------------------------------------------------------------------\n// <auto-generated>\n//     This code was generated by a tool.\n// </auto-generated>\n//------------------------------------------------------------------------------\nnamespace X {}\n", true},
		{"js @generated", "javascript", "/**\n * @generated SignedSource<<abc123>>\n */\nexport default {};\n", true},
		{"rust auto-generated", "rust", "// auto-generated by bindgen\npub struct Foo;\n", true},
		{"protoc cpp", "cpp", "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n#include <string>\n", true},
		{"unknown language", "cobol", "* Generated by something. DO NOT EDIT.\n", false},
		{"empty content", "go", "", false},
	}
	for _, tc := range cases {
		if got := projectdetect.IsGeneratedContent([]byte(tc.content), tc.lang); got != tc.want {
			t.Errorf("%s: IsGeneratedContent(lang=%q) = %v, want %v", tc.name, tc.lang, got, tc.want)
		}
	}
}

func TestIsGeneratedContent_LineBudget(t *testing.T) {
	// Marker after a 12-line license header: within budget, fires.
	header := strings.Repeat("// Copyright 2026 The Authors.\n", 12)
	withMarker := header + "\n// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n"
	if !projectdetect.IsGeneratedContent([]byte(withMarker), "go") {
		t.Error("marker after a 12-line license header should be detected")
	}

	// Marker on line 25: past the 20-line budget, must not fire.
	deep := strings.Repeat("// filler comment line\n", 24) + "// Code generated by tool. DO NOT EDIT.\npackage api\n"
	if projectdetect.IsGeneratedContent([]byte(deep), "go") {
		t.Error("marker past the line budget should not be detected")
	}
}

func TestIsGeneratedContent_Binary(t *testing.T) {
	bin := make([]byte, 1024)
	copy(bin, "// code generated ")
	bin[100] = 0x00
	if projectdetect.IsGeneratedContent(bin, "go") {
		t.Error("binary content (NUL in head) should never be flagged generated")
	}
}

func TestGeneratedMatcher_Custom(t *testing.T) {
	// A fresh empty matcher matches nothing until patterns/markers are added.
	m := projectdetect.NewGeneratedMatcher()
	if m.MatchPath("api/user.pb.go") {
		t.Error("empty matcher should match no path")
	}
	if m.MatchContent([]byte("// Code generated by x. DO NOT EDIT.\n"), "go") {
		t.Error("empty matcher should match no content")
	}

	if err := m.AddPathPattern(`\.tmpl\.go$`); err != nil {
		t.Fatal(err)
	}
	if !m.MatchPath("web/pages.tmpl.go") {
		t.Error("custom path pattern should match")
	}

	m.AddMarker("go", "// autogenerated by our-tool")
	if !m.MatchContent([]byte("// AUTOGENERATED BY our-tool\npackage x\n"), "go") {
		t.Error("custom marker should match case-insensitively")
	}

	// Match combines both signals, inferring language from the path.
	if !m.Match("web/pages.tmpl.go", nil) {
		t.Error("Match should fire on the path signal")
	}
	if !m.Match("pkg/thing.go", []byte("// autogenerated by our-tool\npackage x\n")) {
		t.Error("Match should fire on the content signal")
	}
	if m.Match("pkg/thing.go", []byte("package x\n")) {
		t.Error("Match should not fire when neither signal matches")
	}

	// A bad pattern is reported and nothing is added.
	if err := m.AddPathPattern(`([`); err == nil {
		t.Error("expected error for invalid regexp")
	}
}

func TestDefaultGeneratedMatcher_Independent(t *testing.T) {
	m := projectdetect.DefaultGeneratedMatcher()
	if err := m.AddPathPattern(`(^|/)my-unique-gen-marker/`); err != nil {
		t.Fatal(err)
	}
	m.AddMarker("go", "// my unique local marker")

	if !m.MatchPath("x/my-unique-gen-marker/f.go") {
		t.Error("added pattern should match on the local matcher")
	}
	if projectdetect.IsGeneratedPath("x/my-unique-gen-marker/f.go") {
		t.Error("adding to a DefaultGeneratedMatcher instance must not affect IsGeneratedPath")
	}
	if projectdetect.IsGeneratedContent([]byte("// my unique local marker\n"), "go") {
		t.Error("adding a marker to a local matcher must not affect IsGeneratedContent")
	}
}

func TestRegisterGenerated(t *testing.T) {
	if err := projectdetect.RegisterGeneratedPathPattern(`(^|/)testdata-gen-xyzzy/`); err != nil {
		t.Fatal(err)
	}
	if !projectdetect.IsGeneratedPath("a/testdata-gen-xyzzy/f.go") {
		t.Error("registered pattern should affect package-level IsGeneratedPath")
	}

	projectdetect.RegisterGeneratedMarker("go", "// emitted by xyzzy-compiler")
	if !projectdetect.IsGeneratedContent([]byte("// Emitted by XYZZY-compiler\npackage x\n"), "go") {
		t.Error("registered marker should affect package-level IsGeneratedContent")
	}

	// IsGenerated combines both signals.
	if !projectdetect.IsGenerated("api/user.pb.go", nil) {
		t.Error("IsGenerated should fire on the path signal")
	}
	if !projectdetect.IsGenerated("pkg/mocks.go", []byte("// Code generated by mockery. DO NOT EDIT.\npackage mocks\n")) {
		t.Error("IsGenerated should fire on the content signal")
	}
	if projectdetect.IsGenerated("pkg/engine.go", []byte("package engine\n")) {
		t.Error("IsGenerated should not fire on plain source")
	}
}
